name: Update README.md

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Update README.md
        run: npm run update-readme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "solidsnk86"
          git config user.email "calcagni.gabriel86@gmail.com"
          git add README.md gh-stats.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "🤖[neoBot] Updated README with latest github stats data"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
